import Card from "react-bootstrap/Card";
import {useState} from "react";
const MonthlyReturns = (props) => {
    const [showReturns, setShowReturns] = useState(false);

    const returnResults = <tbody>
                    <tr>
                        <td>
                            2023
                        </td>
                        <td>
                            0.5
                        </td>
                        <td>
                            -1.2
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                    </tr>
                <tr>
                        <td>
                            2023
                        </td>
                        <td>
                            0.5
                        </td>
                        <td>
                            -1.2
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                        <td>
                            2023
                        </td>
                    </tr>
                </tbody>

    return(
        <Card>
            <table onClick={() => setShowReturns(!showReturns)} style={{cursor: "pointer"}}>
                <thead>
                    <tr>
                        <td>
                            Date
                        </td>
                        <td>
                            January
                        </td>
                        <td>
                            February
                        </td>
                        <td>
                            March
                        </td>
                        <td>
                            April
                        </td>
                        <td>
                            May
                        </td>
                        <td>
                            June
                        </td>
                        <td>
                            July
                        </td>
                        <td>
                            August
                        </td>
                        <td>
                            September
                        </td>
                        <td>
                            October
                        </td>
                        <td>
                            November
                        </td>
                        <td>
                            December
                        </td>
                    </tr>
                </thead>
                {showReturns ? returnResults: ''}
            </table>
        </Card>
    )
};
export default MonthlyReturns;